/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardProductsImport } from './routes/dashboard/products'
import { Route as DashboardPermisionariosImport } from './routes/dashboard/permisionarios'
import { Route as DashboardMonitoreoImport } from './routes/dashboard/monitoreo'
import { Route as DashboardLtrImport } from './routes/dashboard/ltr'
import { Route as DashboardClientesImport } from './routes/dashboard/clientes'
import { Route as DashboardAsignacionImport } from './routes/dashboard/asignacion'
import { Route as DashboardLTRIndexImport } from './routes/dashboard/LTR/index'
import { Route as DashboardDBTestIndexImport } from './routes/Dashboard/DBTest/index'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardProductsRoute = DashboardProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardPermisionariosRoute = DashboardPermisionariosImport.update({
  id: '/permisionarios',
  path: '/permisionarios',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardMonitoreoRoute = DashboardMonitoreoImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardLtrRoute = DashboardLtrImport.update({
  id: '/ltr',
  path: '/ltr',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardClientesRoute = DashboardClientesImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardAsignacionRoute = DashboardAsignacionImport.update({
  id: '/asignacion',
  path: '/asignacion',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardLTRIndexRoute = DashboardLTRIndexImport.update({
  id: '/LTR/',
  path: '/LTR/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardDBTestIndexRoute = DashboardDBTestIndexImport.update({
  id: '/Dashboard/DBTest/',
  path: '/Dashboard/DBTest/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/asignacion': {
      id: '/dashboard/asignacion'
      path: '/asignacion'
      fullPath: '/dashboard/asignacion'
      preLoaderRoute: typeof DashboardAsignacionImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/ltr': {
      id: '/dashboard/ltr'
      path: '/ltr'
      fullPath: '/dashboard/ltr'
      preLoaderRoute: typeof DashboardLtrImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/monitoreo': {
      id: '/dashboard/monitoreo'
      path: '/monitoreo'
      fullPath: '/dashboard/monitoreo'
      preLoaderRoute: typeof DashboardMonitoreoImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/permisionarios': {
      id: '/dashboard/permisionarios'
      path: '/permisionarios'
      fullPath: '/dashboard/permisionarios'
      preLoaderRoute: typeof DashboardPermisionariosImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/Dashboard/DBTest/': {
      id: '/Dashboard/DBTest/'
      path: '/Dashboard/DBTest'
      fullPath: '/Dashboard/DBTest'
      preLoaderRoute: typeof DashboardDBTestIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/LTR/': {
      id: '/dashboard/LTR/'
      path: '/LTR'
      fullPath: '/dashboard/LTR'
      preLoaderRoute: typeof DashboardLTRIndexImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteRouteChildren {
  DashboardAsignacionRoute: typeof DashboardAsignacionRoute
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardLtrRoute: typeof DashboardLtrRoute
  DashboardMonitoreoRoute: typeof DashboardMonitoreoRoute
  DashboardPermisionariosRoute: typeof DashboardPermisionariosRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLTRIndexRoute: typeof DashboardLTRIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAsignacionRoute: DashboardAsignacionRoute,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardLtrRoute: DashboardLtrRoute,
  DashboardMonitoreoRoute: DashboardMonitoreoRoute,
  DashboardPermisionariosRoute: DashboardPermisionariosRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLTRIndexRoute: DashboardLTRIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/asignacion': typeof DashboardAsignacionRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/ltr': typeof DashboardLtrRoute
  '/dashboard/monitoreo': typeof DashboardMonitoreoRoute
  '/dashboard/permisionarios': typeof DashboardPermisionariosRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/Dashboard/DBTest': typeof DashboardDBTestIndexRoute
  '/dashboard/LTR': typeof DashboardLTRIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/asignacion': typeof DashboardAsignacionRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/ltr': typeof DashboardLtrRoute
  '/dashboard/monitoreo': typeof DashboardMonitoreoRoute
  '/dashboard/permisionarios': typeof DashboardPermisionariosRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/Dashboard/DBTest': typeof DashboardDBTestIndexRoute
  '/dashboard/LTR': typeof DashboardLTRIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/asignacion': typeof DashboardAsignacionRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/ltr': typeof DashboardLtrRoute
  '/dashboard/monitoreo': typeof DashboardMonitoreoRoute
  '/dashboard/permisionarios': typeof DashboardPermisionariosRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/Dashboard/DBTest/': typeof DashboardDBTestIndexRoute
  '/dashboard/LTR/': typeof DashboardLTRIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/asignacion'
    | '/dashboard/clientes'
    | '/dashboard/ltr'
    | '/dashboard/monitoreo'
    | '/dashboard/permisionarios'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/Dashboard/DBTest'
    | '/dashboard/LTR'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/asignacion'
    | '/dashboard/clientes'
    | '/dashboard/ltr'
    | '/dashboard/monitoreo'
    | '/dashboard/permisionarios'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard'
    | '/Dashboard/DBTest'
    | '/dashboard/LTR'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/asignacion'
    | '/dashboard/clientes'
    | '/dashboard/ltr'
    | '/dashboard/monitoreo'
    | '/dashboard/permisionarios'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/Dashboard/DBTest/'
    | '/dashboard/LTR/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DashboardDBTestIndexRoute: typeof DashboardDBTestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DashboardDBTestIndexRoute: DashboardDBTestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/Dashboard/DBTest/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/asignacion",
        "/dashboard/clientes",
        "/dashboard/ltr",
        "/dashboard/monitoreo",
        "/dashboard/permisionarios",
        "/dashboard/products",
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/LTR/"
      ]
    },
    "/dashboard/asignacion": {
      "filePath": "dashboard/asignacion.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/clientes": {
      "filePath": "dashboard/clientes.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/ltr": {
      "filePath": "dashboard/ltr.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/monitoreo": {
      "filePath": "dashboard/monitoreo.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/permisionarios": {
      "filePath": "dashboard/permisionarios.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/products": {
      "filePath": "dashboard/products.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/Dashboard/DBTest/": {
      "filePath": "Dashboard/DBTest/index.tsx"
    },
    "/dashboard/LTR/": {
      "filePath": "dashboard/LTR/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
